services:
  api:
    image: abhinavmohan12/gpay-api:latest   # ✅ Docker Hub image
    container_name: gpay-api                # ✅ Local container name
    ports:
      - "8000:8000"
    volumes:
      - ./tokens:/app/tokens
      - ./credentials.json:/app/credentials.json:ro
      - ./.env:/app/.env:ro
    restart: always

  poller:
    image: abhinavmohan12/gpay-poller:latest
    container_name: gpay-poller
    volumes:
      - ./tokens:/app/tokens
      - ./credentials.json:/app/credentials.json:ro
      - ./.env:/app/.env:ro
    restart: always