version: "3.9"

services:
  api:
    build: .
    image: abhinavmohan12/gpay-api:latest
    container_name: gpay-api
    command: uvicorn gemini_test:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./tokens:/app/tokens
      - ./credentials.json:/app/credentials.json:ro
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  poller:
    build: .
    image: abhinavmohan12/gpay-poller:latest
    container_name: gpay-poller
    command: python GoogleDrivePoll.py
    volumes:
      - .:/app
      - ./tokens:/app/tokens
      - ./credentials.json:/app/credentials.json:ro
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
      
  nginx:
    image: nginx:latest
    container_name: gpay-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot
    container_name: gpay-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"
    restart: always